jazzband/django-analytical

- README.rst
This is just a minor correction of vocabulary (not really grammar)
> Corrected verb, added link to PRs

- analytical/templatetags/uservoice.py
- docs/services/uservoice.rst
This PR adds support to indentigy users in the Uservoice service. it Includes some docs
> Identifying authenticated users in Uservoice

- analytical/templatetags/mixpanel.py
- analytical/tests/test_tag_mixpanel.py
- docs/services/mixpanel.rst
See https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.identify for reference
> update mixpanel indetify code.

- README.rst
* Remove co-maintainer note
* Add headers
> Update README (co-maintainer, headers)

- .travis.yml
- tox.ini
Plus white-space changes to match typically used YAML syntax (indentation of lists).
This commit may close issue #54 if all goes well.
> Also test with Django 1.8 (Travis-CI)

- README.rst
Clickable badges:
* current PyPI package version number
* Travis-CI build status
* downloads per month from PyPI
* license info
> Add beautiful badges to README

- analytical/templatetags/piwik.py
- analytical/tests/test_tag_piwik.py
- docs/services/piwik.rst
Since Piwik support custom variables, I patched the Piwik templatetag to support them.
> Add Piwik user variables support

- .travis.yml
- README.rst
- tox.ini
Discovered this today. Very sweet!
> Add "Python versions" badge (README)

- .travis.yml
- analytical/templatetags/crazy_egg.py
- analytical/templatetags/google_analytics.py
- analytical/templatetags/gosquared.py
- analytical/templatetags/intercom.py
- analytical/templatetags/spring_metrics.py
- analytical/templatetags/woopra.py
- analytical/tests/test_tag_gosquared.py
- analytical/tests/test_utils.py
- analytical/utils.py
* Fix some code smells (redefine built-in, unused import) [reported by Landscape](https://landscape.io/github/jcassee/django-analytical/14/messages/smell).
* Address `flake8` complaints in touched modules (except for some specific overly long lines).
Looking forward to seeing code health go up bit!
> Fix some code smells reported by Landscape

- README.rst
- analytical/templatetags/analytical.py
- analytical/templatetags/yandex_metrica.py
- analytical/tests/test_tag_yandex_metrica.py
- docs/install.rst
- docs/services/yandex_metrica.rst
> Support Yandex.Metrica

- README.rst
- analytical/templatetags/analytical.py
- analytical/templatetags/rating_mailru.py
- analytical/tests/test_tag_rating_mailru.py
- docs/install.rst
- docs/services/rating_mailru.rst
> Add support for the Rating@Mail.ru service

- docs/features.rst
- docs/history.rst
- docs/index.rst
- docs/install.rst
- docs/services.rst
- docs/settings.rst
- docs/tutorial.rst
- Use code-block directive for snippets
- Correct whitespace and spacing between sentences.
- Update URLs (http -> https)
> [Docs] Overhaul of reST syntax

- README.rst
- analytical/templatetags/analytical.py
- analytical/templatetags/facebook_pixel.py
- analytical/tests/test_tag_facebook_pixel.py
- docs/install.rst
- docs/services/facebook_pixel.rst
This adds support for Facebook Pixel, with tests and docs.
> Add Facebook Pixel support

- .travis.yml
- analytical/templatetags/intercom.py
- analytical/templatetags/woopra.py
- analytical/utils.py
- setup.py
- tox.ini
> Use user.is_authenticated for Django 2.0 compatibility.

- README.rst
- analytical/templatetags/analytical.py
- analytical/templatetags/hotjar.py
- analytical/tests/test_tag_hotjar.py
- docs/services/hotjar.rst
This adds straightforward support for the Hotjar tracking code.
> Add Hotjar support

- analytical/templatetags/piwik.py
- analytical/tests/test_tag_piwik.py
- docs/services/piwik.rst
This option disables cookies -- it's off by default.
See also: https://matomo.org/faq/general/faq_157/
> Add PIWIK_DISABLE_COOKIES.

- AUTHORS.rst
- CONTRIBUTING.rst
- README.rst
- docs/index.rst
- docs/install.rst
- docs/services.rst
- setup.py
This PR implements the guidelines required to transfer the project to the Jazzband organization.
Fixes jazzband/roadies#116.
> Implement Jazzband guidelines

- .gitignore
- pyproject.toml
- tox.ini
Just a little cleanup and modernization of `tox.ini` with moving some configuration bits to `pyproject.toml`.
> Consolidate tox.ini and pyproject.toml

- setup.py
I feel ashamed that it took me 3 attempts to get it (probably) right. But I feel it was maybe worth it. [PEP20](https://peps.python.org/pep-0020/) says it all.
> Readability counts, code must be self-explanatory

- analytical/templatetags/google_analytics_js.py
- docs/services/google_analytics_js.rst
fixes https://github.com/jazzband/django-analytical/issues/212
> add GOOGLE_ANALYTICS_JS_SOURCE setting to allow custom source URL

- README.rst
- docs/services/clickmap.rst
Heads-up @kobus-v-schoor, @philippeowagner.
Fixes #182.
> Fix outdated URLs that point to the Clickmap service

- CHANGELOG.rst
- analytical/templatetags/woopra.py
- docs/services/woopra.rst
- tests/unit/test_tag_woopra.py
> Add more config options for Woopra

- CHANGELOG.rst
- analytical/__init__.py
This is to prepare a new release on PyPI.
If I remember correctly, I need to merge this PR and only then push a version tag on the resulting commit on the `main` branch.
In accordance with the current Git tags in this repo, this will be `v3.2.0` (note the leading `v`). Does this look fine for you all?
- [Jazzband Releases](https://jazzband.co/about/releases#continuous-integration)
> Release v3.2.0
