jazzband/django-analytical

.travis.yml, analytical/templatetags/clickmap.py, analytical/templatetags/hubspot.py, analytical/tests/settings.py, analytical/tests/test_tag_chartbeat.py, analytical/tests/test_tag_clickmap.py, analytical/tests/test_tag_clicky.py, analytical/tests/test_tag_crazy_egg.py, analytical/tests/test_tag_gauges.py, analytical/tests/test_tag_google_analytics.py, analytical/tests/test_tag_gosquared.py, analytical/tests/test_tag_hubspot.py, analytical/tests/test_tag_intercom.py, analytical/tests/test_tag_kiss_insights.py, analytical/tests/test_tag_kiss_metrics.py, analytical/tests/test_tag_mixpanel.py, analytical/tests/test_tag_olark.py, analytical/tests/test_tag_optimizely.py, analytical/tests/test_tag_performable.py, analytical/tests/test_tag_piwik.py, analytical/tests/test_tag_reinvigorate.py, analytical/tests/test_tag_snapengage.py, analytical/tests/test_tag_spring_metrics.py, analytical/tests/test_tag_uservoice.py, analytical/tests/test_tag_woopra.py, analytical/tests/test_utils.py, analytical/tests/utils.py, analytical/utils.py, setup.py, tox.ini
* Added Django 1.7 to tox/travis (confirmed tox works, guessing for travis).
* Test failures became apparent in clickmap which have been fixed.
* Removed override_settings to django function instead (also removed with/without_apps as rarely used), required for Django 1.7 as the code copied from django does not honor the new app loading system.
=> Add Django 1.7 support

.travis.yml, analytical/templatetags/analytical.py, analytical/tests/test_tag_intercom.py, analytical/tests/test_utils.py, tox.ini
Fixed the exception problem that was presenting problems for python >= 3.0. Changed some testing assertions, where possible, that have been deprecated in new versions of python. All of the tox tests are passing, as are all builds in the Travis build matrix.
=> Adding python 3 compatibility

analytical/utils.py, docs/_ext/local.py, docs/conf.py, setup.py
These changes fix mainly whitespace complaints by `flake8` everywhere except in the `templatetags` und the `tests` folder, i.e.
```
$ flake8 --exclude=templatetags,tests
```
runs without complaints.
=> Fix flake8 complaints (except for templatetags and tests)

README.rst
* Travis/Github sometimes yields a broken badge image with a query parameter (should now be better)
* The image's ALT text was "develop", which is wrong of course
=> Remove wrong branch name from Build Status badge

setup.py
Part of my confusion in #59 was to see no reference to python 3 in `setup.py` . Added
=> mark the package python 3 compatible

.coveragerc, .gitignore, .travis.yml, README.rst, tox.ini
We have pretty great test coverage, so let's advertise that!
This change does drop the `-Wall` option to `python setup.py test`. I could not determine how to tell the `coverage` script how to pass it to `python`. Is that important?
=> Calculate coverage and send to Coveralls.io

docs/services/google_analytics.rst
The old link just 404s at the moment.
=> Update link to Google's Site Speed documentation

analytical/templatetags/analytical.py
Does away with the deprecation warning displayed by Django 1.8 (e.g. with a runserver).
The implementation is backward compatible. Django's `django.utils.importlib` is only needed for Python 2.6 (e.g. in combination with Django 1.6), because Python's `importlib` core library is not available for Python lower than 2.7+.
=> Fix RemovedInDjango19Warning (django.utils.importlib)

docs/services/google_analytics.rst
Looks like the `google_analytics` module was moved into `templatetags` some time ago and the documentation wasn't updated with it.
=> Update locations of constants in Google Analytics documentation

README.rst
A commit adding the Gitter badge on top of the README, and some text in the Documentation section.
The URL changes are due to changes from HTTP to HTTPS of GitHub and packages.python.org (redirects to pythonhosted.org, but I like packages.python.org; sounds more official).
=> Add Gitter badge, update some URLs

analytical/tests/test_utils.py, analytical/utils.py
I wanted to be able to set `ANALYTICAL_INTERNAL_IPS=[]` on my development machine, however when the list is empty it doesn't properly override what is in `INTERNAL_IPS`. This PR aims to fix that.
=> override internal ips with empty list

analytical/templatetags/piwik.py
A simple change to the regular expression safeguarding the definition of a Piwiki server URL. Required an actual, public server name (domain with top-level domain) earlier. Now this limitation has been removed (i.e. local server names such as `localhost` are allowed); longer server names are still checked for syntactical plausibility.
Closes #76
=> Allow local host names for Piwik servers

analytical/tests/test_utils.py, analytical/utils.py, tox.ini
This change is to make `get_identity` work when using a custom user model with an alternative username field. It gracefully handles versions of Django that don't support alternative username fields.
=> support alternative username fields

README.rst, docs/history.rst
I believe the paragraph on Django support is better placed in the History chapter of the documentation. Makes the README unnecessarily verbose.
BTW, I adore your clean structure (allowing both self-explaining files in the project root and inclusion in the docs) with AUTHORS, CHANGELOG, LICENSE.
=> Move comment on Django support from README to history

analytical/templatetags/google_analytics.py, analytical/templatetags/woopra.py
Fixes the two worst offenders, currently. With some additional PEP8 corrections (white space).
I know using `locals()` is maybe elegant, but explicit is better than implicit. Landscape agrees.
=> Fix more code smells reported by Landscape

analytical/templatetags/google_analytics.py, analytical/tests/test_tag_google_analytics.py, docs/services/google_analytics.rst
I added support for GA's `_setSampleRate` and `_setSiteSpeedSampleRate` settings for my needs and then saw `_setSessionCookieTimeout` and `_setVisitorCookieTimeout` would be easy to add too.
I've updated the tests and the docs and thought it might be of interest to other developers.
Thanks for this project!
Steve
=> Google Analytics _set*SampleRate and _set*CookieTimeout

analytical/templatetags/woopra.py
To track custom events, like SPA routing, the global variable `woopra` is needed in the browser. (e.g. https://github.com/angulartics/angulartics) 
I took the latest JavaScript snippet from https://www.woopra.com/docs/setup/javascript-tracking/#basic as the updated async source.
=> Add woopra to window for SPA analytics

CHANGELOG.rst, README.rst, docs/install.rst, docs/services/rating_mailru.rst
Prevent 'Raiting&#64;Mail.ru' from appearing as mailto link.
=> Escape the '@' symbol in doc

analytical/templatetags/piwik.py, analytical/tests/test_tag_piwik.py
Small addition allowing a domain port with the Piwik module's domain regex. Ran into this when setting up django-analytical and Piwik for a project.
=> Added optional port to Piwik domain path

analytical/templatetags/piwik.py, analytical/tests/test_tag_piwik.py
Avoids mixed content issues when using django-analytical on sites served
over HTTPS. Using a protocol-relative URL is also recommended in the
Piwik documentation: https://issues.piwik.org/344.
Fixes #96.
=> Use protocol-relative URL for Piwik fallback img

analytical/templatetags/intercom.py, analytical/tests/test_tag_intercom.py
Intercom has updated their ID to include characters a-z.
=> Updated regex for Intercom APP_ID and tests for Intercom

analytical/tests/test_tag_uservoice.py, analytical/tests/test_utils.py, analytical/utils.py
A config variable may not necessarily be None when not configured. Can be stored in the database with the help of proxy objects, which can  return the None value when accessed.
For example, to integrate with jazzband/django-constance.
=> Fix holding config variable in database through proxy objects

.travis.yml, CHANGELOG.rst, analytical/__init__.py, setup.py, tox.ini
This PR
- reduces the build matrix to officially supported combinations (as discussed in PR #114)
- adds information about dropped Python support to the change log
=> Fix non-critical issues forgotten for v2.3.0

.travis.yml, tox.ini
Converting the README.rst to HTML sometimes fails on PyPI and causes unreadable package descriptions on PyPI. This PR adds a check to tox and Travis, which verifies that the package description on PyPI will be generated correctly.
=> Check PyPI package description generation w/ tox

.travis.yml, tox.ini
With this change we use the somewhat dedicated approach for checking for a correct .rst -> .html conversion before packaging. Seen at https://github.com/jazzband/pip-tools/pull/608.
=> Use more targeted approach for README conversion check

docs/services/intercom.rst
The old link 404s: the new link is the closest replacement I can find.
=> Intercom docs: Fix broken link for custom data

README.rst, docs/install.rst, docs/services/piwik.rst
See [Piwik is now Matomo – Announcement](https://matomo.org/blog/2018/01/piwik-is-now-matomo/)
=> docs: Piwik is now Matomo

analytical/templatetags/intercom.py, analytical/tests/test_tag_intercom.py
This removes the check in the code that limits the Intercom widget to authenticated users. I'm not sure why the check was there: Intercom is intended for use with both anonymous and authenticated users.
This also updates the Intercom tests to add a conventional `test_render_internal_ip`.
=> Enable Intercom for anonymous users

analytical/templatetags/intercom.py, analytical/tests/test_tag_intercom.py, docs/services/intercom.rst
This adds support for Intercom's HMAC identity verification, as documented here:
https://www.intercom.com/help/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product
This adds a new optional setting: `INTERCOM_HMAC_SECRET_KEY`
This also sets a default `user_id` field for Django-authenticated users (which is what the HMAC authenticates, falling back to the `email` field).
=> Support Intercom HMAC identity verification

analytical/templatetags/analytical.py, analytical/templatetags/google_analytics.py, analytical/templatetags/google_analytics_js.py, analytical/tests/test_tag_google_analytics_js.py, docs/services/google_analytics_js.rst
This PR adds the support of the the new [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/) library from Google.
It provides a new `google_analytics_js` tag, which is included if the `GOOGLE_ANALYTICS_JS_PROPERTY_ID` is set. For backwards compatibility, and since it is intended to completely replace the legacy `ga.js` library, the settings are set using the same `GOOGLE_ANALYTICS_` prefix.
=> Basic support of Google analytics.js, #108

.travis.yml, analytical/templatetags/intercom.py, tox.ini
This PR fixes two problems:
* Remove the typing hints from `intercom.py` because they cause warnings in flake8. We cannot import the typing names because they don't exist in Python 2.
* Use the xenial distribution for the readme test. Django now requires Sqlite version 3.8.3 or higher, which is not available on trusty.
=> Fix flake8 and readme tests

.gitignore, analytical/__init__.py, docs/_ext/local.py, setup.py, tox.ini
* Ensure Tox target clean is working (execution order)
* Ensure Tox target docs is working (remove deprecated reference)
* Update packaging information (Django 2.2, license)
* Remove problematic install_requires from setup
=> Ensure Tox targets clean and docs are working

AUTHORS.rst, LICENSE.txt, analytical/templatetags/analytical.py, analytical/templatetags/matomo.py, analytical/templatetags/piwik.py, analytical/tests/test_tag_matomo.py, docs/install.rst, docs/services/matomo.rst, docs/services/piwik.rst
With the rebranding of Piwik to Matomo, this commit:
* copies the piwik module to matomo and rebrands
* notes that the piwik module is deprecated
* updates the javascript to the current Matomo version
Fixes #132
=> Create Matomo module; leave Piwik to be deprecated

analytical/templatetags/google_analytics_js.py
In #127 I made sure that the old `ga.js` analytics code used the proper ordering of calls. It seems that the new `analytics.js` code introduced by #135 has the same issue.
Currently it renders:
```
ga('create', 'UA-25383750-9', 'auto', {});
 
ga('send', 'pageview');
ga('set', 'anonymizeIp', true);
```
The send method should happen as last method call however.
I checked the contents of the `{commands}` placeholder, and it can only consist of `ga('set', ...)` commands.
=> Make sure new Google Analytics anonimyze IP calls also happen before sending pageviews

docs/services/matomo.rst, docs/services/piwik.rst
There is a small typo in docs/services/matomo.rst, docs/services/piwik.rst.
Should read `between` rather than `betweeen`.
=> docs: Fix simple typo, betweeen -> between

analytical/templatetags/analytical.py, analytical/templatetags/google_analytics_gtag.py, analytical/tests/test_tag_google_analytics_gtag.py, docs/services/google_analytics_gtag.rst
This PR adds the support of the the new [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs/) library from Google.
It provides a new `google_analytics_gtag` tag, which is included if the `GOOGLE_ANALYTICS_GTAG_PROPERTY_ID` is set. There are yet not settings supported.
=> Add basic support of Google gtag.js

.travis.yml
The `deploy` stage was excluded by error, as I shifted the blocks around to get better readability. That's why there was no release triggered to PyPI when I pushed a tag. – Let's retry. :smirk:
=> Travis CI: Include deploy stage (excluded by error)

analytical/templatetags/analytical.py, analytical/templatetags/google_analytics_gtag.py, analytical/tests/templatetags/dummy.py, analytical/tests/test_tag_analytical.py, analytical/tests/test_tag_google_analytics_gtag.py, docs/services/google_analytics_gtag.rst
This commit adds user_id support for the gtag google analytics implementation.
=> Add user_id to Google Analytics GTag

analytical/templatetags/piwik.py
Code so far emits a warning to all users about about Piwik being
deprecated, even if Piwik is not being used.
Scope the warning so it only triggers for people to whom it's relevant.
=> Only show piwik warning if using piwik

analytical/templatetags/google_analytics_gtag.py, analytical/tests/test_tag_google_analytics_gtag.py, docs/services/google_analytics_gtag.rst
The new App+Web feature of Google Analytics uses Measurement ID, which has a different pattern then UA property ID. Currently the code was not accepting measurement IDs due to a regex check which I have changed to incorporate the Measurement ID pattern.
Fixes #163
=> Updated regex for gtag to accept measurement ID

docs/install.rst
Adds the missing details on SnapEngage to the [Installation and configuration](https://django-analytical.readthedocs.io/en/latest/install.html) section of the docs.
Thanks @johnmathews for bringing this to our attention!
Fixes #166
=> Add SnapEngage details to Installation section

analytical/templatetags/hotjar.py, analytical/tests/test_tag_hotjar.py
This is almost only aesthetical. Let's remove some indentation to save a few bytes of white-space.
=> Reduce indentation of Hotjar JS code

docs/install.rst, docs/services/google_analytics_js.rst
Similar to #166, it seems like both Google Analytics Universal Analytics and Google Analytics JS integration have been added w/o extending the [install section](https://django-analytical.readthedocs.io/en/latest/install.html#enabling-the-services) in our docs.
=> Add missing Google Analytics instructions to install section

README.rst, analytical/templatetags/analytical.py, analytical/templatetags/luckyorange.py, docs/install.rst, docs/services/luckyorange.rst, tests/unit/test_tag_luckyorange.py
Adds a new integration for a service similar to Hotjar.
Fixes #172
=> Add Lucky Orange integration

CHANGELOG.rst, analytical/__init__.py
As mentioned in #178, the new release will be a major one, as we drop Python 2 support.
Reference for the change log: https://github.com/jazzband/django-analytical/compare/v2.6.0...master
=> Release v3.0.0

tests/unit/test_tag_analytical.py, tests/unit/test_tag_chartbeat.py, tests/unit/test_tag_clickmap.py, tests/unit/test_tag_clicky.py, tests/unit/test_tag_crazy_egg.py, tests/unit/test_tag_facebook_pixel.py, tests/unit/test_tag_gauges.py, tests/unit/test_tag_google_analytics.py, tests/unit/test_tag_google_analytics_gtag.py, tests/unit/test_tag_google_analytics_js.py, tests/unit/test_tag_gosquared.py, tests/unit/test_tag_hotjar.py, tests/unit/test_tag_hubspot.py, tests/unit/test_tag_intercom.py, tests/unit/test_tag_kiss_insights.py, tests/unit/test_tag_kiss_metrics.py, tests/unit/test_tag_luckyorange.py, tests/unit/test_tag_matomo.py, tests/unit/test_tag_mixpanel.py, tests/unit/test_tag_olark.py, tests/unit/test_tag_optimizely.py, tests/unit/test_tag_performable.py, tests/unit/test_tag_piwik.py, tests/unit/test_tag_rating_mailru.py, tests/unit/test_tag_snapengage.py, tests/unit/test_tag_spring_metrics.py, tests/unit/test_tag_uservoice.py, tests/unit/test_tag_woopra.py, tests/unit/test_tag_yandex_metrica.py, tests/unit/test_utils.py
When looking at the code when it is formatted with Black there are a number of cases where it would be a bit more readable if plain pytest asserts were used. 
I've done a few files as an example. Is this wanted? Let me know what you think.
=> Migrate tests to Pytest plain asserts

.github/workflows/test.yml, setup.py, tox.ini
Hey, hope all is well. 
This PR adds Python 3.10 supprt and also drops support from Django 3.1 which is now EOL. 
Following review and merge of this do you think we could issue a new release to confirm support of these new versions?
=> Add Python 3.10 and drop Django 3.1

.github/workflows/check.yml, .github/workflows/test.yml, README.rst, setup.py
Following the example of other popular free software projects, we also rename our default branch to remove terminology stemming from colonialism and slavery.
Closes #204
=> Rename default branch (master ➜ main)

setup.py
pathlib's Path is the more elegant, object-oriented approach for path operations, available since Python 3.6.
We have dropped support for Python < 3.6 for quite a while, so using it for installing the package should be fine.
=> Use pathlib instead of os.path (we only support Python 3.6+)

setup.py
We better close the file explicitly after reading. A context manager does it for us in an elegant fashion.
Follow-up on #207.
=> Use context manager for file reading

CHANGELOG.rst, analytical/__init__.py, setup.py
Updated the change log  and removed optional license field from metadata, as [recommended in the packaging guide](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license).
=> Release v3.1.0

tests/unit/test_utils.py
Overriding a user identity is implemented in our code, but it's not covered by tests yet.
**Historical note:** The tests result from a discussion in the obsolete PR #189.
=> Add custom identity test

analytical/templatetags/google_analytics_gtag.py, tests/unit/test_tag_google_analytics_gtag.py
Add the missing prefix in `get_identity()` in `google_analytics_gtag` and test it.
Change of docs and other tests will come in separate PRs.
=> Add the missing get_identity prefix to google_analytics_gtag, test it

docs/services/spring_metrics.rst
There is a small typo in docs/services/spring_metrics.rst.
Should read `conversions` rather than `convesions`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, convesions -> conversions

.coveragerc, .github/workflows/release.yml, .github/workflows/test.yml, docs/history.rst, pyproject.toml, tox.ini
Fixes a broken text include in the History chapter introduced via commit 7704f8c.
Removes the coverage configuration file and configures textual coverage report output in GHA test jobs.
=> Fix broken author credits in documentation, show coverage report in GHA jobs
